name: Vue Build and Deploy to S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
    
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
          
      - name: Copy files to S3 with AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
        working-directory: ./dist
        run: |
         aws s3 sync . s3://north-simcoe/ --delete
