name: Deploy to AWS

on:
  push:
    branches: [main]  
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
   
    - name: Install and build
      run: |
        npm install
        npm run build
       
    - name: Sync to S3  
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}  
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ca-central-1'  
        SOURCE_DIR: 'dist'    

    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@v1.3
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: '/*'
        AWS_REGION: 'ca-central-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
